server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false
      #剔除时间
    eviction-interval-timer-in-ms: 60000
spring:
  application:
    name: ek